# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts (we run our own build)
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the application using tsup
RUN npm run build

# Expose port 3333 by default (HTTP mode if needed)
EXPOSE 3333

# Default command to run in stdio mode for MCP
CMD ["node", "dist/index.js", "--stdio"]
